development:
  adapter: postgresql
  database: videoapi_development
  pool: 5
  timeout: 5000
  username:shanaweitzen
  password: Tinydancer28
test:
  adapter: postgresql
  database: videoapi_test
  pool: 5
  timeout: 5000
  username: shanaweitzen
  password: Tinydancer28

production:
  adapter: postgresql
  database: videoapi_production
  pool: 5
  timeout: 5000
  username: shanaweitzen
  password: Tinydancer28